spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customerBD?createDatabaseIfNotExist=true&useSSL=false
    password: ''
    #driverClassName: org.h2.Driver
  h2:
    console:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: update
    show-sql: 'true'
